<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-RJ1TA7IM" failures="1" tests="4" name="Create Customer API test" time="5.901" errors="0" timestamp="30 Apr 2020 13:35:00 GMT">
  <testcase classname="com.amit.APITestingFramework.testcases.CreateCustommerTest" name="validateCreateCustomerAPIWithInValidSecretKey" time="3.248">
    <failure type="java.lang.AssertionError" message="expected [200] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at com.amit.APITestingFramework.testcases.CreateCustommerTest.validateCreateCustomerAPIWithInValidSecretKey(CreateCustommerTest.java:41)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- validateCreateCustomerAPIWithInValidSecretKey -->
  <testcase classname="com.amit.APITestingFramework.testcases.CreateCustommerTest" name="validateCreateCustomerAPIWithValidSecretKey" time="2.43"/>
  <testcase classname="com.amit.APITestingFramework.testcases.CreateCustommerTest" name="validateCreateCustomerAPIWithValidSecretKey" time="2.562"/>
  <testcase classname="com.amit.APITestingFramework.testcases.CreateCustommerTest" name="validateCreateCustomerAPIWithValidSecretKey" time="2.599"/>
</testsuite> <!-- Create Customer API test -->
