<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-RJ1TA7IM" failures="1" tests="4" name="com.amit.APITestingFramework.testcases.DeleteCustomerTest" time="8.954" errors="0" timestamp="30 Apr 2020 13:04:31 GMT" skipped="0">
  <testcase classname="com.amit.APITestingFramework.testcases.DeleteCustomerTest" name="deleteCustomer" time="2.237"/>
  <testcase classname="com.amit.APITestingFramework.testcases.DeleteCustomerTest" name="deleteCustomer" time="2.237">
    <failure message="ID key is not present in the JSON response expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: ID key is not present in the JSON response expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.amit.APITestingFramework.testcases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:45)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
  <testcase classname="com.amit.APITestingFramework.testcases.DeleteCustomerTest" name="deleteCustomer" time="2.239"/>
  <testcase classname="com.amit.APITestingFramework.testcases.DeleteCustomerTest" name="deleteCustomer" time="2.241"/>
</testsuite> <!-- com.amit.APITestingFramework.testcases.DeleteCustomerTest -->
